import { Card, Select, Space, Table, Tag, Typography } from "antd";

type Column = { mappingKey: string; sheet: string; column: string; header?: string; type: string };
type Field = { field: string; type: string; quality_status?: string; quality_messages?: string[]; non_empty_rate?: number };

export function MappingCenter({ columns, fields, mapping, fieldOptions, onMappingChange, qualityFilter, onQualityFilterChange }: { columns: Column[]; fields: Field[]; mapping: Record<string, string>; fieldOptions: { label: string; value: string }[]; onMappingChange: (key: string, value: string) => void; qualityFilter: string; onQualityFilterChange: (value: string) => void }) {
  const sheets = [...new Set(columns.map((column) => column.sheet))];
  const filteredFields = fields.filter((field) => qualityFilter === "all" || field.quality_status === qualityFilter);
  return <div className="mapping-center-grid"><Card className="mapping-sheet-panel" bodyStyle={{ padding: 0 }}><div className="mapping-panel-title">模板结构</div><div className="mapping-panel-body"><Typography.Text type="secondary">{columns.length} 个输出列</Typography.Text>{sheets.map((sheet) => <div className="mapping-sheet-item active" key={sheet}><span>{sheet}</span><Tag>{columns.filter((column) => column.sheet === sheet).length}</Tag></div>)}</div></Card><Card className="mapping-rule-panel" bodyStyle={{ padding: 0 }}><div className="mapping-panel-title">输出列映射</div><div className="mapping-panel-body"><Table size="small" rowKey="mappingKey" dataSource={columns} pagination={false} scroll={{ x: 620 }} columns={[{ title: "Sheet", dataIndex: "sheet" }, { title: "列", dataIndex: "column" }, { title: "模板表头", dataIndex: "header" }, { title: "类型", dataIndex: "type" }, { title: "基础数据来源", render: (_: unknown, item: Column) => item.type === "formula" ? <Tag color="orange">模板公式锁定</Tag> : <Select showSearch allowClear value={mapping[item.mappingKey]} onChange={(value) => onMappingChange(item.mappingKey, value ?? "")} options={fieldOptions} placeholder="选择字段" /> }]} /></div></Card><Card className="mapping-field-panel" bodyStyle={{ padding: 0 }}><div className="mapping-panel-title">基础字段质量</div><div className="mapping-panel-body"><Space direction="vertical" className="wide"><Select value={qualityFilter} onChange={onQualityFilterChange} options={[{ label: "全部字段", value: "all" }, { label: "正常字段", value: "healthy" }, { label: "警告字段", value: "warning" }, { label: "错误字段", value: "error" }]} /><Typography.Text type="secondary">显示 {filteredFields.length} / {fields.length} 个字段</Typography.Text>{filteredFields.map((field) => <div className="field-quality-row" key={field.field}><Space><Typography.Text strong>{field.field}</Typography.Text><Tag color={field.quality_status === "error" ? "red" : field.quality_status === "warning" ? "gold" : "green"}>{field.type}</Tag></Space><Typography.Text type="secondary">非空率 {field.non_empty_rate == null ? "-" : `${Math.round(field.non_empty_rate * 100)}%`}</Typography.Text><Typography.Text type="secondary">{field.quality_messages?.join("；") || "质量通过"}</Typography.Text></div>)}</Space></div></Card></div>;
}
