import React, { useEffect, useState } from "react";
import { Alert, Button, Card, Dropdown, Form, Input, InputNumber, Layout, Menu, Modal, Progress, Select, Space, Steps, Table, Tabs, Tag, Typography, Upload, message } from "antd";
import { UploadOutlined } from "@ant-design/icons";
import axios from "axios";
import ReactFlow, { Background, Controls, MiniMap, addEdge, applyEdgeChanges, applyNodeChanges, type Connection, type Edge, type Node, type NodeChange, type EdgeChange } from "reactflow";
import "reactflow/dist/style.css";
import { EmptyState } from "./components/EmptyState";
import { GenerationWizard } from "./components/GenerationWizard";
import { PageHeader } from "./components/PageHeader";
import { StatusBadge } from "./components/StatusBadge";
import { MappingPage } from "./components/MappingPage";
import { WorkbookProfileModal } from "./components/WorkbookProfileModal";
import { WorkflowPathGuide } from "./components/WorkflowPathGuide";
import { NoticeWorkflowConfigModal, type NoticeWorkflowConfig } from "./components/NoticeWorkflowConfigModal";
import { WorkflowModeCenter } from "./components/WorkflowModeCenter";
import { NativeWorkflowImprovements } from "./components/NativeWorkflowImprovements";
import { WorkflowModeSetup } from "./components/WorkflowModeSetup";

const api = axios.create({ baseURL: "/api" });
type Template = { id: number; name: string; version: string; parent_template_id?: number; has_formula: boolean; sheet_count: number; is_example?: boolean; created_at: string };
type TemplateVersions = { template_id: number; root_template_id: number; versions: Template[] };
 type Workflow = { id: number; name: string; mode: string; template_id: number; column_mapping: Record<string, string>; notice_config?: NoticeWorkflowConfig; notice_config_version?: number; is_example?: boolean; node_json?: { nodes: Node[]; edges: Edge[] } };
type DataSource = { id: number; name: string; schema_: Record<string, { type: string; quality_status?: string; quality_messages?: string[]; non_empty_rate?: number }> };
type Task = { id: number; workflow_id: number; data_source_id: number; status: string; mapping_snapshot_id?: number; error_log?: string; calculation_engine?: string; output_sha256?: string; started_at?: string; finished_at?: string };
type PreviewSheet = { title: string; rows: unknown[][] };
type FormulaPreview = { formula_count: number; sheets: { title: string; formula_count: number; results: { cell: string; formula: string; value: unknown; error?: string | null }[] }[] };
type FormulaDependencies = { formula_count: number; dependencies: { sheet: string; cell: string; formula: string; references: { sheet: string; cell: string }[] }[] };
type QualityReport = { row_count: number; field_count: number; issue_count: number; valid: boolean; fields: { field: string; rows: number; missing: number; types: string[] }[]; issues: { field: string; type: string; message: string }[] };
type Tutorial = { scenario: string; complexity: string; title: string; content: string };
type FinalPreview = { sheet_count: number; sheets: { title: string; max_row: number; max_column: number; rows: unknown[][] }[] };
type NoticeConfig = { title: string; period: string; publisher: string; as_of_date: string; signature: string; notes: string };
type BatchSummary = { batch_id: string; task_count: number; pending_count: number; success_count: number; failed_count: number; status: string; quality_issue_count: number; quality_invalid_count: number; quality_checked_count: number; notice_config: NoticeConfig; tasks: { id: number; data_source_id: number; status: string; output_path: boolean; output_sha256?: string }[] };
type AuditPreview = { task_id: number; output_sha256?: string; events: { id: number; action: string; detail?: string; created_at: string }[] };
type MappingTrace = { task_id: number; workflow_name: string; mode: string; template_version: string; mapping_rule_version?: number; mapping_snapshot_id?: number; dependency_order: string[]; rules: { target: string; source_kind: string; source_field?: string; expression?: string; dependencies?: string[]; operator?: string; value?: unknown }[] };
type WorkflowMatch = { workflow_id: number; workflow_name: string; score: number; missing_fields: string[]; reasons: string[] };
type WorkbenchSummary = { counts: { templates: number; workflows: number; data_sources: number; successful_tasks: number }; attention: { failed_tasks: number; quality_issues: number; running_tasks: number }; recent_tasks: { id: number; status: string; workflow_id: number; data_source_id: number; finished_at?: string }[] };
type WorkbookAnalysis = { template_id: number; template_version: string; sheets: { title: string; role_candidates?: { role: string; reason: string }[]; max_row: number; max_column: number; formula_count: number; data_start_row_candidate?: number; field_header_row_candidate?: number; field_headers?: { column: string; header: string }[]; formula_risks?: { type: string; count: number; message: string }[] }[]; recommended_profile: Record<string, unknown> };
type MappingPreview = { columns: { target: string; sheet: string; column: string; header: string; type: string; is_formula: boolean; formula?: string }[]; fields: { field: string; type: string; quality_status?: string; quality_messages?: string[]; non_empty_rate?: number }[]; recommendations: { target: string; status: string; candidates: { field: string; score: number; reason: string; type_compatible: boolean }[] }[]; validation: { valid: boolean; errors: { target?: string; type: string; message: string }[]; warnings: { type: string; message: string }[]; dependency_order: string[]; mapped_count: number; required_count: number; error_count: number; warning_count: number; field_quality?: Record<string, { status: string; messages: string[] }> } };

function App() {
  const [page, setPage] = useState("dashboard");
  const goToMappingCenter = () => setPage("mapping-center");
  const [templates, setTemplates] = useState<Template[]>([]);
  const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [dataSources, setDataSources] = useState<DataSource[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [selected, setSelected] = useState<Template>();
  const [columns, setColumns] = useState<any[]>([]);
  const [workflow, setWorkflow] = useState<Workflow>();
  const [mapping, setMapping] = useState<Record<string, string>>({});
  const [dataSourceId, setDataSourceId] = useState<number>();
  const [batchSourceIds, setBatchSourceIds] = useState<number[]>([]);
  const [batchTaskIds, setBatchTaskIds] = useState<number[]>([]);
  const [task, setTask] = useState<Task>();
  const [error, setError] = useState<string>();
  const [preview, setPreview] = useState<PreviewSheet[]>([]);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [formulaReport, setFormulaReport] = useState<{ formula_count: number; valid: boolean; issues?: { message: string }[] }>();
  const [formulaPreview, setFormulaPreview] = useState<FormulaPreview>();
  const [formulaDependencies, setFormulaDependencies] = useState<FormulaDependencies>();
  const [qualityReport, setQualityReport] = useState<QualityReport>();
  const [templateVersions, setTemplateVersions] = useState<TemplateVersions>();
  const [dagNodes, setDagNodes] = useState<Node[]>([]);
  const [dagEdges, setDagEdges] = useState<Edge[]>([]);
  const [selectedDagNodeId, setSelectedDagNodeId] = useState<string>();
  const [tutorials, setTutorials] = useState<Tutorial[]>([]);
  const [tutorial, setTutorial] = useState<Tutorial>();
  const [finalPreview, setFinalPreview] = useState<FinalPreview>();
  const [noticeConfig, setNoticeConfig] = useState<NoticeConfig>({ title: "Excel 通报表", period: "", publisher: "", as_of_date: "", signature: "", notes: "" });
  const [noticeConfigOpen, setNoticeConfigOpen] = useState(false);
  const [batches, setBatches] = useState<BatchSummary[]>([]);
  const [auditPreview, setAuditPreview] = useState<AuditPreview>();
  const [mappingTrace, setMappingTrace] = useState<MappingTrace>();
  const [workflowMatches, setWorkflowMatches] = useState<WorkflowMatch[]>([]);
  const [wizardStep, setWizardStep] = useState(0);
  const [workbench, setWorkbench] = useState<WorkbenchSummary>();
  const [mappingPreview, setMappingPreview] = useState<MappingPreview>();
  const [mappingSnapshotId, setMappingSnapshotId] = useState<number>();
  const [mappingQualityFilter, setMappingQualityFilter] = useState("all");
  const [mappingFocusTarget, setMappingFocusTarget] = useState<string>();
  const [pendingWorkflowId, setPendingWorkflowId] = useState<number>();
  const [noticeWorkflowConfig, setNoticeWorkflowConfig] = useState<{ workflowId: number; config?: NoticeWorkflowConfig }>();
  const [workflowModeIntent, setWorkflowModeIntent] = useState("template_native");
  const [noticeWorkflowHistory, setNoticeWorkflowHistory] = useState<{ version: number; config: NoticeWorkflowConfig }[]>();
  const [noticePreview, setNoticePreview] = useState<{ values: Record<string, Record<string, unknown>>; totals: Record<string, unknown>; traces: { row: number; metric: string; matched_rows: number; value: unknown }[] }>();
  const [loading, setLoading] = useState(true);
  const [workbookAnalysis, setWorkbookAnalysis] = useState<WorkbookAnalysis>();
  const [preflight, setPreflight] = useState<{ valid: boolean; missing_fields?: string[]; required_fields?: string[]; formula_risks?: { message: string; count: number }[] }>();
  const draftKey = "excel-flow-generation-draft";

  const load = async () => {
    try {
      const [templatesResponse, workflowsResponse, sourcesResponse, tasksResponse, tutorialsResponse, batchesResponse, workbenchResponse] = await Promise.all([
        api.get<Template[]>("/templates"), api.get<Workflow[]>("/workflows"), api.get<DataSource[]>("/data-sources"), api.get<Task[]>("/tasks"), api.get<{ tutorials: Tutorial[] }>("/examples/tutorials"), api.get<{ batches: BatchSummary[] }>("/tasks/batches"), api.get<WorkbenchSummary>("/workbench/summary"),
      ]);
      setTemplates(templatesResponse.data); setWorkflows(workflowsResponse.data); setDataSources(sourcesResponse.data); setTasks(tasksResponse.data);
      setTutorials(tutorialsResponse.data.tutorials);
      setBatches(batchesResponse.data.batches);
      setWorkbench(workbenchResponse.data);
      setError(undefined);
    } catch (reason) { showError(reason); } finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, []);
  useEffect(() => {
    try {
      const draft = JSON.parse(window.localStorage.getItem(draftKey) ?? "null") as { page?: string; dataSourceId?: number; workflowId?: number; wizardStep?: number; noticeConfig?: NoticeConfig } | null;
      if (!draft) return;
       if (draft.page) setPage(draft.page === "mapping" ? "mapping-center" : draft.page);
      if (draft.dataSourceId) setDataSourceId(draft.dataSourceId);
      if (draft.workflowId) setPendingWorkflowId(draft.workflowId);
      if (typeof draft.wizardStep === "number") setWizardStep(draft.wizardStep);
      if (draft.noticeConfig) setNoticeConfig(draft.noticeConfig);
    } catch { window.localStorage.removeItem(draftKey); }
  }, []);
  useEffect(() => {
    if (!pendingWorkflowId) return;
    const restored = workflows.find((item) => item.id === pendingWorkflowId);
    if (restored) { setWorkflow(restored); setPendingWorkflowId(undefined); }
  }, [pendingWorkflowId, workflows]);
  useEffect(() => {
    if (page !== "tasks" || task?.status === "success") return;
    window.localStorage.setItem(draftKey, JSON.stringify({ page, dataSourceId, workflowId: workflow?.id, wizardStep, noticeConfig }));
  }, [dataSourceId, draftKey, noticeConfig, page, task?.status, wizardStep, workflow?.id]);
  useEffect(() => {
    if (task?.status === "success") window.localStorage.removeItem(draftKey);
  }, [draftKey, task?.status]);
  useEffect(() => {
    if (!task || ["success", "failed"].includes(task.status)) return;
    const timer = window.setInterval(async () => {
      try {
        const response = await api.get<Task>(`/tasks/${task.id}/status`);
        setTask(response.data);
        if (["success", "failed"].includes(response.data.status)) { window.clearInterval(timer); void load(); }
      } catch (reason) { window.clearInterval(timer); showError(reason); }
    }, 1000);
    return () => window.clearInterval(timer);
  }, [task?.id, task?.status]);

  const showError = (reason: unknown) => {
    const detail = axios.isAxiosError(reason) ? reason.response?.data?.detail : "操作失败";
    setError(detail); message.error(detail);
  };
  const upload = async (endpoint: string, file: File) => {
    const body = new FormData(); body.append("file", file);
    try { const response = await api.post(endpoint, body); if (endpoint.includes("data-sources") && response.data?.id) { setDataSourceId(response.data.id); setWizardStep(1); } await load(); message.success("上传成功"); } catch (reason) { showError(reason); }
    return false;
  };
  const uploadTemplate = async (file: File, parent?: Template) => {
    const body = new FormData(); body.append("file", file); body.append("version", parent ? `${Number(parent.version) + 0.1}` : "1.0"); if (parent) body.append("parent_template_id", String(parent.id));
    try { await api.post("/templates/upload", body); await load(); message.success("模板版本上传成功"); } catch (reason) { showError(reason); }
    return false;
  };
  const showColumns = async (item: Template) => {
    setSelected(item);
    const response = await api.get(`/templates/${item.id}/columns`);
    const sheets = response.data.sheets ?? [];
    setColumns(sheets.flatMap((sheet: { title: string; columns: any[] }) => sheet.columns.map((column) => ({ ...column, sheet: sheet.title, mappingKey: `${sheet.title}!${column.column}` }))));
  };
  const showPreview = async (item: Template) => { try { const response = await api.get(`/templates/${item.id}/preview`); setPreview(response.data.sheets); setPreviewOpen(true); } catch (reason) { showError(reason); } };
  const showFormulaReport = async (item: Template) => { try { const [validation, dependencies] = await Promise.all([api.get(`/formulas/${item.id}/validate`), api.get<FormulaDependencies>(`/formulas/${item.id}/dependencies`)]); setFormulaReport(validation.data); setFormulaDependencies(dependencies.data); } catch (reason) { showError(reason); } };
  const createWorkflow = async () => { if (!selected) return; try { const response = await api.post("/workflows", { template_id: selected.id, name: `${selected.name} 模式A`, mode: "formula" }); setWorkflow(response.data); setMapping({}); goToMappingCenter(); await load(); } catch (reason) { showError(reason); } };
  const createNativeWorkflow = async (item: Template) => { try { const response = await api.post<Workflow>("/workflows", { template_id: item.id, name: `${item.name} 模板原生通报`, mode: "template_native" }); setSelected(item); setWorkflow(response.data); setMapping({}); setPage("tasks"); await load(); } catch (reason) { showError(reason); } };
  const createDagWorkflow = async (item: Template) => { try { await showColumns(item); const response = await api.post<Workflow>("/workflows", { template_id: item.id, name: `${item.name} 模式B`, mode: "dag" }); setSelected(item); setWorkflow(response.data); setDagNodes([]); setDagEdges([]); setPage("dag"); await load(); } catch (reason) { showError(reason); } };
  const configureTemplate = async (item: Template) => { await showColumns(item); try { const response = await api.post<Workflow>("/workflows", { template_id: item.id, name: `${item.name} 模式A`, mode: "formula" }); setSelected(item); setWorkflow(response.data); setMapping(response.data.column_mapping ?? {}); goToMappingCenter(); await load(); } catch (reason) { showError(reason); } };
  const openWorkflow = async (item: Workflow) => { const template = templates.find((entry) => entry.id === item.template_id); if (item.mode === "template_native") { setSelected(template); setWorkflow(item); setMapping(item.column_mapping ?? {}); setPage("tasks"); return; } if (template) await showColumns(template); setWorkflow(item); setMapping(item.column_mapping ?? {}); goToMappingCenter(); };
  const openNoticeWorkflowConfig = async (item: Workflow) => { try { const response = await api.get<{ config: NoticeWorkflowConfig }>(`/workflows/${item.id}/notice-config`); setNoticeWorkflowConfig({ workflowId: item.id, config: response.data.config }); } catch (reason) { showError(reason); } };
  const saveNoticeWorkflowConfig = async (config: NoticeWorkflowConfig) => { if (!noticeWorkflowConfig) return; try { await api.put(`/workflows/${noticeWorkflowConfig.workflowId}/notice-config`, config); setNoticeWorkflowConfig(undefined); await load(); message.success("通报配置已保存为新版本"); } catch (reason) { showError(reason); } };
  const previewNoticeWorkflow = async () => { if (!noticeWorkflowConfig || !dataSourceId) return message.warning("请先选择基础明细"); try { const response = await api.post(`/workflows/${noticeWorkflowConfig.workflowId}/notice-config/preview?data_source_id=${dataSourceId}`); setNoticePreview(response.data); } catch (reason) { showError(reason); } };
  const loadNoticeHistory = async () => { if (!noticeWorkflowConfig) return; try { const response = await api.get<{ history: { version: number; config: NoticeWorkflowConfig }[] }>(`/workflows/${noticeWorkflowConfig.workflowId}/notice-config/history`); setNoticeWorkflowHistory(response.data.history); } catch (reason) { showError(reason); } };
  const restoreNoticeHistory = async (version: number) => { if (!noticeWorkflowConfig) return; try { const response = await api.post<{ config: NoticeWorkflowConfig }>(`/workflows/${noticeWorkflowConfig.workflowId}/notice-config/restore/${version}`); setNoticeWorkflowConfig({ ...noticeWorkflowConfig, config: response.data.config }); setNoticeWorkflowHistory(undefined); await load(); message.success("历史配置已恢复为新版本"); } catch (reason) { showError(reason); } };
  const openDagWorkflow = async (item: Workflow) => { const template = templates.find((entry) => entry.id === item.template_id); if (template) await showColumns(template); setWorkflow(item); setDagNodes((item.node_json?.nodes ?? []).map((node) => ({ ...node, type: "default", data: { ...node.data, nodeType: node.data?.nodeType ?? node.type, config: node.data?.config ?? {} } }))); setDagEdges(item.node_json?.edges ?? []); setPage("dag"); };
  const addDagNode = (type: string) => { const id = `${type}-${Date.now()}`; const config = type === "formula" ? { field: "total", expression: "amount * 2" } : type === "condition" ? { field: "total", operator: "greater_than", value: 0 } : type === "write_template" ? { mapping: {} } : {}; setDagNodes((current) => [...current, { id, type: "default", position: { x: 80 + current.length * 40, y: 80 + current.length * 40 }, data: { label: type, nodeType: type, config } }]); setSelectedDagNodeId(id); };
  const updateDagNodeConfig = (config: Record<string, unknown>) => { if (!selectedDagNodeId) return; setDagNodes((current) => current.map((node) => node.id === selectedDagNodeId ? { ...node, data: { ...node.data, config } } : node)); };
  const selectedDagNode = dagNodes.find((node) => node.id === selectedDagNodeId);
  const selectedDagConfig = (selectedDagNode?.data.config ?? {}) as Record<string, any>;
  const selectedDagSourceId = dagNodes.find((node) => node.data.nodeType === "data_source")?.data.config?.source_id as number | undefined;
  const dagSource = dataSources.find((source) => source.id === selectedDagSourceId);
  const dagSourceFields = Object.keys(dagSource?.schema_ ?? {});
  const dagAvailableFields = [...new Set([...dagSourceFields, ...dagNodes.filter((node) => node.data.nodeType === "formula").map((node) => node.data.config?.field).filter(Boolean)])];
  const templateFieldOptions = columns.filter((column) => column.type !== "formula").map((column) => ({ label: `${column.sheet}!${column.column} ${column.header ?? ""}`, value: `${column.sheet}!${column.column}` }));
  const suggestedField = (column: any) => { const header = String(column.header ?? "").toLowerCase(); return dagSourceFields.find((field) => field.toLowerCase() === header) ?? dagSourceFields.find((field) => header && (field.toLowerCase().includes(header) || header.includes(field.toLowerCase()))); };
  const renderDagConfigForm = () => {
    if (!selectedDagNode) return <Typography.Text type="secondary">点击画布节点编辑配置</Typography.Text>;
    const type = selectedDagNode.data.nodeType;
    if (type === "data_source") return <Form layout="vertical"><Form.Item label="数据源"><Select value={selectedDagConfig.source_id} placeholder="选择数据源" options={dataSources.map((source) => ({ label: source.name, value: source.id }))} onChange={(value) => updateDagNodeConfig({ ...selectedDagConfig, source_id: value })} /></Form.Item></Form>;
    if (type === "formula") return <Form layout="vertical"><Form.Item label="输出字段"><Select showSearch value={selectedDagConfig.field} options={dagAvailableFields.map((field) => ({ label: field, value: field }))} onChange={(value) => updateDagNodeConfig({ ...selectedDagConfig, field: value })} /></Form.Item><Form.Item label="表达式"><Input value={selectedDagConfig.expression} placeholder="例如 amount * 2" onChange={(event) => updateDagNodeConfig({ ...selectedDagConfig, expression: event.target.value })} /></Form.Item></Form>;
    if (type === "condition") return <Form layout="vertical"><Form.Item label="判断字段"><Select showSearch value={selectedDagConfig.field} options={dagAvailableFields.map((field) => ({ label: field, value: field }))} onChange={(value) => updateDagNodeConfig({ ...selectedDagConfig, field: value })} /></Form.Item><Form.Item label="比较方式"><Select value={selectedDagConfig.operator} options={[{ label: "等于", value: "equals" }, { label: "不等于", value: "not_equals" }, { label: "大于", value: "greater_than" }, { label: "小于", value: "less_than" }]} onChange={(value) => updateDagNodeConfig({ ...selectedDagConfig, operator: value })} /></Form.Item><Form.Item label="比较值"><InputNumber value={selectedDagConfig.value} onChange={(value) => updateDagNodeConfig({ ...selectedDagConfig, value })} /></Form.Item></Form>;
    if (type === "field_mapping") return <Form layout="vertical">{columns.filter((column) => column.type !== "formula").map((column) => { const key = `${column.sheet}!${column.column}`; const value = selectedDagConfig.mapping?.[key] ?? suggestedField(column); return <Form.Item key={key} label={`${key} ${column.header ?? ""}`}><Select showSearch allowClear value={value} options={dagSourceFields.map((field) => ({ label: field, value: field }))} onChange={(next) => updateDagNodeConfig({ ...selectedDagConfig, mapping: { ...(selectedDagConfig.mapping ?? {}), [key]: next } })} /></Form.Item>; })}</Form>;
    if (type === "write_template") return <Form layout="vertical">{columns.filter((column) => column.type !== "formula").map((column) => { const key = `${column.sheet}!${column.column}`; const value = selectedDagConfig.mapping?.[key] ?? suggestedField(column); return <Form.Item key={key} label={`${key} ${column.header ?? ""}`}><Select showSearch allowClear value={value} options={dagSourceFields.map((field) => ({ label: field, value: field }))} onChange={(next) => updateDagNodeConfig({ ...selectedDagConfig, mapping: { ...(selectedDagConfig.mapping ?? {}), [key]: next } })} /></Form.Item>; })}</Form>;
    return <Typography.Text type="secondary">此节点无需额外配置</Typography.Text>;
  };
  const saveDag = async () => { if (!workflow) return; try { const persistedNodes = dagNodes.map((node) => { const nodeType = node.data.nodeType; const config = node.data.config ?? {}; if (!["field_mapping", "write_template"].includes(nodeType)) return { ...node, type: nodeType, data: { ...node.data, nodeType, config, label: node.data.label } }; const mapping = { ...(config.mapping ?? {}) }; columns.filter((column) => column.type !== "formula").forEach((column) => { const key = `${column.sheet}!${column.column}`; if (!mapping[key]) mapping[key] = suggestedField(column); }); return { ...node, type: nodeType, data: { ...node.data, nodeType, config: { ...config, mapping }, label: node.data.label } }; }); const response = await api.put(`/workflows/${workflow.id}/dag`, { nodes: persistedNodes, edges: dagEdges }); setWorkflow(response.data.workflow); setDagNodes(persistedNodes); message.success("模式 B 流程已保存"); await load(); } catch (reason) { showError(reason); } };
  const handleDagNodesChange = (changes: NodeChange[]) => { setDagNodes((current) => applyNodeChanges(changes, current)); const removedIds = new Set(changes.filter((change) => change.type === "remove").map((change) => change.id)); if (removedIds.size) setDagEdges((current) => current.filter((edge) => !removedIds.has(edge.source) && !removedIds.has(edge.target))); };
  const handleDagEdgesChange = (changes: EdgeChange[]) => setDagEdges((current) => applyEdgeChanges(changes, current));
  const saveMapping = async () => { if (!workflow) return; try { const response = await api.put(`/workflows/${workflow.id}/mapping`, { column_mapping: mapping }); setWorkflow(response.data); message.success("映射已保存"); } catch (reason) { showError(reason); } };
  const previewMapping = async () => {
    if (!selected || !dataSourceId) return message.warning("请先选择模板和基础数据");
    const rules = Object.entries(mapping).filter(([, source]) => source).map(([target, source_field]) => ({ target, source_kind: "field", source_field }));
    try {
      const response = await api.post<MappingPreview>("/workflows/mapping/preview", { template_id: selected.id, data_source_id: dataSourceId, rules });
      setMappingPreview(response.data);
      setWizardStep(2);
    } catch (reason) { showError(reason); }
  };
  const saveMappingSnapshot = async () => {
    if (!workflow || !dataSourceId || !mappingPreview?.validation.valid) return message.warning("请先完成映射预检");
    const rules = Object.entries(mapping).filter(([, source]) => source).map(([target, source_field]) => ({ target, source_kind: "field", source_field }));
    try {
      const response = await api.post<{ id: number }>(`/workflows/${workflow.id}/mapping-snapshots`, { data_source_id: dataSourceId, rules });
      setMappingSnapshotId(response.data.id);
      message.success("映射快照已保存");
    } catch (reason) { showError(reason); }
  };
  const runTask = async () => { if (!workflow) return message.warning("请先选择工作流"); const sourceId = workflow.mode === "dag" ? selectedDagSourceId : dataSourceId; if (!sourceId) return message.warning("请先配置数据源"); try { const response = await api.post("/tasks/run", { workflow_id: workflow.id, data_source_id: sourceId, mapping_snapshot_id: workflow.mode === "formula" ? mappingSnapshotId : undefined, notice_config: noticeConfig }); setTask(response.data); setPage("history"); await load(); } catch (reason) { showError(reason); } };
  const runBatch = async () => { if (!workflow || batchSourceIds.length === 0) return message.warning("请先选择批量数据源"); try { const response = await api.post<{ tasks: { id: number; status: string }[] }>("/tasks/batch-run", { workflow_id: workflow.id, data_source_ids: batchSourceIds, notice_config: noticeConfig }); setBatchTaskIds(response.data.tasks.filter((item) => item.id).map((item) => item.id)); message.success(`已提交 ${batchSourceIds.length} 个批量任务`); setPage("history"); await load(); } catch (reason) { showError(reason); } };
  const updateNoticeConfig = (key: keyof NoticeConfig, value: string) => setNoticeConfig((current) => ({ ...current, [key]: value }));
  const retryBatch = async (batch: BatchSummary) => { try { const response = await api.post<{ retried_count: number }>(`/tasks/batches/${batch.batch_id}/retry`); message.success(`已重新提交 ${response.data.retried_count} 个失败任务`); await load(); } catch (reason) { showError(reason); } };
  const showAudit = async (item: Task) => { try { const response = await api.get<AuditPreview>(`/tasks/${item.id}/audit`); setAuditPreview(response.data); } catch (reason) { showError(reason); } };
  const showMappingTrace = async (item: Task) => { try { const response = await api.get<MappingTrace>(`/tasks/${item.id}/mapping-trace`); setMappingTrace(response.data); } catch (reason) { showError(reason); } };
  const copyWorkflow = async (item: Workflow) => { try { await api.post(`/workflows/${item.id}/copy`); await load(); message.success("工作流已复制"); } catch (reason) { showError(reason); } };
  const retryTask = async (item: Task) => { try { const response = await api.post(`/tasks/${item.id}/retry`); setTask(response.data); setPage("tasks"); await load(); } catch (reason) { showError(reason); } };
  const showTaskFormulaPreview = async (item: Task) => { try { const response = await api.get<FormulaPreview>(`/tasks/${item.id}/formula-preview`); setFormulaPreview(response.data); } catch (reason) { showError(reason); } };
  const showFinalPreview = async (item: Task) => { try { const response = await api.get<FinalPreview>(`/tasks/${item.id}/final-preview`); setFinalPreview(response.data); } catch (reason) { showError(reason); } };
  const showQualityReport = async () => { if (!dataSourceId) return message.warning("请先选择数据源"); try { const response = await api.get<QualityReport>(`/data-sources/${dataSourceId}/quality-report`); setQualityReport(response.data); setWizardStep(2); } catch (reason) { showError(reason); } };
  const runPreflight = async (workflowId = workflow?.id, sourceId = dataSourceId) => { if (!workflowId || !sourceId) { setPreflight(undefined); return; } try { const response = await api.get(`/tasks/preflight?workflow_id=${workflowId}&data_source_id=${sourceId}`); setPreflight(response.data); } catch (reason) { showError(reason); } };
  const showWorkflowMatches = async () => { if (!dataSourceId) return message.warning("请先选择数据源"); try { const response = await api.get<{ matches: WorkflowMatch[] }>(`/data-sources/${dataSourceId}/workflow-matches`); setWorkflowMatches(response.data.matches); setWizardStep(1); } catch (reason) { showError(reason); } };
  const showVersions = async (item: Template) => { try { const response = await api.get<TemplateVersions>(`/templates/${item.id}/versions`); setTemplateVersions(response.data); } catch (reason) { showError(reason); } };
  const showTutorial = (scenario: string) => { const item = tutorials.find((entry) => entry.scenario === scenario); if (item) setTutorial(item); };
  const analyzeWorkbook = async (item: Template) => { try { const response = await api.post<WorkbookAnalysis>(`/templates/${item.id}/analyze-workbook`); setWorkbookAnalysis(response.data); } catch (reason) { showError(reason); } };
  const saveWorkbookProfile = async (profile: Record<string, unknown>) => { if (!workbookAnalysis) return; try { await api.put(`/templates/${workbookAnalysis.template_id}/workbook-profile`, profile); message.success("模板工作簿配置已保存"); setWorkbookAnalysis(undefined); } catch (reason) { showError(reason); } };

   const activeSource = dataSources.find((source) => source.id === dataSourceId);
   const activeFields = mappingPreview?.fields ?? Object.entries(activeSource?.schema_ ?? {}).map(([field, metadata]) => ({ field, type: metadata.type, quality_status: metadata.quality_status ?? "healthy", quality_messages: metadata.quality_messages ?? [], non_empty_rate: metadata.non_empty_rate }));
   const filteredFields = activeFields.filter((field) => mappingQualityFilter === "all" || field.quality_status === mappingQualityFilter);
   const fieldOptions = filteredFields.map((field) => ({ label: `${field.field} · ${field.type} · ${field.quality_status === "error" ? "错误" : field.quality_status === "warning" ? "警告" : "正常"}`, value: field.field }));
    const mappingCenterPanel = page === "mapping-center" ? <MappingPage workflowName={workflow?.name} columns={columns} fields={activeFields} mapping={mapping} fieldOptions={fieldOptions} qualityFilter={mappingQualityFilter} onBack={() => setPage("templates")} onSave={() => void saveMapping()} onPreview={() => void previewMapping()} onSaveSnapshot={() => void saveMappingSnapshot()} onMappingChange={(key, value) => setMapping({ ...mapping, [key]: value })} onQualityFilterChange={setMappingQualityFilter} /> : null;
   const statusTag = (status: string) => <StatusBadge status={status} />;
  const templateColumns = [
    { title: "名称", render: (_: unknown, item: Template) => <Space>{item.name}{item.is_example && <Tag color="blue">示例</Tag>}</Space> },
    { title: "版本", dataIndex: "version" },
    { title: "公式", render: (_: unknown, item: Template) => item.has_formula ? <Tag color="orange">含公式</Tag> : <Tag>无公式</Tag> },
    { title: "Sheet", dataIndex: "sheet_count" },
      { title: "操作", render: (_: unknown, item: Template) => <Dropdown menu={{ items: [{ key: "analyze", label: "分析工作簿", onClick: () => void analyzeWorkbook(item) }, { key: "columns", label: "查看列", onClick: () => void showColumns(item) }, { key: "preview", label: "预览", onClick: () => void showPreview(item) }, { key: "formula", label: "公式检查", onClick: () => void showFormulaReport(item) }, ...(item.is_example && tutorials.some((tutorialItem) => tutorialItem.scenario === item.name.replace("示例模板：", "")) ? [{ key: "tutorial", label: "查看教程", onClick: () => showTutorial(item.name.replace("示例模板：", "")) }] : []), { key: "versions", label: "版本管理", onClick: () => void showVersions(item) }, { key: "upload", label: <Upload beforeUpload={(file) => uploadTemplate(file, item)} showUploadList={false}><span>上传新版本</span></Upload> }, { key: "mode-a", label: "配置模式 A", onClick: () => void configureTemplate(item) }, { key: "native", label: "配置模板原生通报", onClick: () => void createNativeWorkflow(item) }, { key: "mode-b", label: "配置模式 B", onClick: () => void createDagWorkflow(item) }] }} trigger={["click"]}><Button>更多</Button></Dropdown> },
  ];
      const workflowColumns = [{ title: "名称", render: (_: unknown, item: Workflow) => <Space>{item.name}{item.is_example && <Tag color="blue">示例</Tag>}</Space> }, { title: "模式", render: (_: unknown, item: Workflow) => item.mode === "template_native" ? "模板原生通报" : item.mode }, { title: "操作", render: (_: unknown, item: Workflow) => <Dropdown menu={{ items: [{ key: "view", label: item.mode === "dag" ? "查看流程" : item.mode === "template_native" ? "选择数据生成" : "查看映射", onClick: () => item.mode === "dag" ? openDagWorkflow(item) : void openWorkflow(item) }, ...(item.mode === "template_native" ? [{ key: "edit-notice", label: "编辑通报规则", onClick: () => void openNoticeWorkflowConfig(item) }] : []), { key: "copy", label: item.is_example ? "复制为我的工作流" : "复制", onClick: () => void copyWorkflow(item) }] }} trigger={["click"]}><Button>更多</Button></Dropdown> }];
     const taskColumns = [{ title: "任务", render: (_: unknown, item: Task) => `#${item.id}` }, { title: "状态", render: (_: unknown, item: Task) => statusTag(item.status) }, { title: "计算引擎", dataIndex: "calculation_engine", render: (value: string) => value ?? "未执行" }, { title: "文件指纹", render: (_: unknown, item: Task) => item.output_sha256 ? <Typography.Text copyable={{ text: item.output_sha256 }}>{item.output_sha256.slice(0, 12)}...</Typography.Text> : "未生成" }, { title: "开始", dataIndex: "started_at" }, { title: "完成", dataIndex: "finished_at" }, { title: "操作", render: (_: unknown, item: Task) => <Dropdown menu={{ items: [{ key: "audit", label: "审计", onClick: () => void showAudit(item) }, { key: "trace", label: "映射追溯", onClick: () => void showMappingTrace(item) }, ...(item.status === "success" ? [{ key: "download", label: "下载成品", onClick: () => window.open(`/api/tasks/${item.id}/download`, "_blank") }, { key: "preview", label: "成品预览", onClick: () => void showFinalPreview(item) }, { key: "formula", label: "公式结果", onClick: () => void showTaskFormulaPreview(item) }] : []), ...(["success", "failed"].includes(item.status) ? [{ key: "retry", label: "重试", onClick: () => void retryTask(item) }] : [])] }} trigger={["click"]}><Button>更多</Button></Dropdown> }];
  const previewTabs = preview.map((sheet) => {
    const headers = sheet.rows[0] ?? [];
    const rows = sheet.rows.slice(1).map((row, index) => ({ key: index, values: row }));
    const columnsForSheet = headers.map((_header, index) => ({
      title: String(headers[index] ?? `列 ${index + 1}`),
      render: (_: unknown, item: { values: unknown[] }) => String(item.values[index] ?? ""),
    }));
    return { key: sheet.title, label: sheet.title, children: <Table size="small" pagination={false} dataSource={rows} columns={columnsForSheet} /> };
  });

  const dashboard = <div className="workbench-page"><Card className="hero-card"><Typography.Text className="eyebrow">EXCEL WORKFLOW PLATFORM</Typography.Text><Typography.Title level={2}>从基础数据到成品通报</Typography.Title><Typography.Paragraph>把数据、模板、工作流和结果集中在一条可追溯的生产线上。</Typography.Paragraph><Space wrap><Button type="primary" size="large" onClick={() => setPage("tasks")}>开始生成</Button><Button ghost size="large" onClick={() => setPage("templates")}>进入资产中心</Button><Button type="text" className="hero-link" onClick={() => setPage("history")}>查看结果中心</Button></Space></Card><div className="metric-grid"><Card><Typography.Text type="secondary">模板资产</Typography.Text><Typography.Title level={3}>{workbench?.counts.templates ?? templates.length}</Typography.Title><Typography.Text type="secondary">含版本和公式结构</Typography.Text></Card><Card><Typography.Text type="secondary">可用工作流</Typography.Text><Typography.Title level={3}>{workbench?.counts.workflows ?? workflows.length}</Typography.Title><Typography.Text type="secondary">支持模式 A / B</Typography.Text></Card><Card><Typography.Text type="secondary">已导入数据</Typography.Text><Typography.Title level={3}>{workbench?.counts.data_sources ?? dataSources.length}</Typography.Title><Typography.Text type="secondary">可继续匹配工作流</Typography.Text></Card><Card><Typography.Text type="secondary">成功成品</Typography.Text><Typography.Title level={3}>{workbench?.counts.successful_tasks ?? 0}</Typography.Title><Typography.Text type="secondary">可预览、校验和下载</Typography.Text></Card></div><div className="workbench-columns"><Card title="需要处理" extra={<Button type="link" onClick={() => setPage("history")}>打开结果中心</Button>}><Space direction="vertical" className="wide"><Alert type={workbench?.attention.failed_tasks ? "error" : "success"} message={`${workbench?.attention.failed_tasks ?? 0} 个失败任务`} description="失败任务可以从批次列表中重试。" showIcon /><Alert type={workbench?.attention.quality_issues ? "warning" : "success"} message={`${workbench?.attention.quality_issues ?? 0} 个数据质量问题`} description="在生成向导中打开质量预检和报告。" showIcon /></Space></Card><Card title="推荐工作流"><Steps direction="vertical" size="small" items={[{ title: "导入基础数据", description: "上传 CSV 或 XLSX 文件" }, { title: "选择或创建工作流", description: "按字段结构查看匹配结果" }, { title: "配置通报并生成", description: "预览成品后导出文件" }]} /></Card></div></div>;
   const wizardPanel = <GenerationWizard step={wizardStep} dataSourceId={dataSourceId} dataSources={dataSources} workflows={workflows} workflowId={workflow?.id} workflowName={workflow?.name} noticeConfig={noticeConfig} preflight={preflight} onUpload={(file) => upload("/data-sources/upload", file)} onSourceChange={(value) => { setDataSourceId(value); setWizardStep(1); void runPreflight(workflow?.id, value); }} onWorkflowChange={(value) => { const next = workflows.find((item) => item.id === value); setWorkflow(next); setWizardStep(2); void runPreflight(value, dataSourceId); }} onMatch={() => void showWorkflowMatches()} onQuality={() => void showQualityReport()} onNotice={() => setNoticeConfigOpen(true)} onGenerate={() => void runTask()} canGenerate={Boolean(workflow && dataSourceId && (workflow.mode !== "template_native" || preflight?.valid))} />;
   const workflowMatchPanel = workflowMatches.length > 0 ? <Card className="wizard-match-panel" title="推荐工作流"><Table size="small" rowKey="workflow_id" pagination={false} dataSource={workflowMatches} columns={[{ title: "工作流", dataIndex: "workflow_name" }, { title: "匹配度", render: (_: unknown, item: WorkflowMatch) => `${Math.round(item.score * 100)}%` }, { title: "缺失字段", render: (_: unknown, item: WorkflowMatch) => item.missing_fields.length ? item.missing_fields.join(", ") : "字段完整" }, { title: "操作", render: (_: unknown, item: WorkflowMatch) => <Button disabled={item.missing_fields.length > 0} onClick={() => { const selectedWorkflow = workflows.find((entry) => entry.id === item.workflow_id); if (selectedWorkflow) { setWorkflow(selectedWorkflow); setWizardStep(2); void runPreflight(selectedWorkflow.id, dataSourceId); } }}>选择</Button> }]} /></Card> : null;
    const pathGuide = page === "dashboard" ? <WorkflowPathGuide onConfigure={() => setPage("templates")} onGenerate={() => setPage("tasks")} /> : null;
     const modeCenter = page === "modes" ? <WorkflowModeCenter workflows={workflows} templates={templates} onOpen={(mode) => { setWorkflowModeIntent(mode); setPage("mode-setup"); }} onWorkflow={(item) => { void openWorkflow(item); }} /> : null;
    const modeSetup = page === "mode-setup" ? <WorkflowModeSetup mode={workflowModeIntent} templates={templates} onBack={() => setPage("modes")} onSelect={(item) => { if (workflowModeIntent === "template_native") void createNativeWorkflow(item); else if (workflowModeIntent === "dag") void createDagWorkflow(item); else if (workflowModeIntent === "formula") { void configureTemplate(item); } else { void api.post<Workflow>("/workflows", { template_id: item.id, name: `${item.name} 手工配置`, mode: "manual" }).then((response) => { setWorkflow(response.data); setSelected(item); setPage("mapping-center"); void load(); }).catch(showError); } }} /> : null;
     const assetToolbar = page === "templates" ? <Card className="asset-toolbar-card"><Typography.Text type="secondary">模板中心支持版本管理、Sheet 预览、公式检查、教程和四种工作流模式配置。</Typography.Text></Card> : null;
    const workbookProfilePanel = <><WorkbookProfileModal analysis={workbookAnalysis} open={Boolean(workbookAnalysis)} onClose={() => setWorkbookAnalysis(undefined)} onSave={saveWorkbookProfile} /><NoticeWorkflowConfigModal open={Boolean(noticeWorkflowConfig)} config={noticeWorkflowConfig?.config} onCancel={() => setNoticeWorkflowConfig(undefined)} onSave={saveNoticeWorkflowConfig} onPreview={() => void previewNoticeWorkflow()} onHistory={() => void loadNoticeHistory()} /><Modal title="通报指标预览" open={Boolean(noticePreview)} onCancel={() => setNoticePreview(undefined)} footer={null} width={1000}>{noticePreview && <Table size="small" pagination={false} rowKey={(item) => `${item.row}-${item.metric}`} dataSource={noticePreview.traces} columns={[{ title: "组织行", dataIndex: "row" }, { title: "指标", dataIndex: "metric" }, { title: "匹配行数", dataIndex: "matched_rows" }, { title: "计算结果", dataIndex: "value" }]} />}</Modal><Modal title="通报配置历史" open={Boolean(noticeWorkflowHistory)} onCancel={() => setNoticeWorkflowHistory(undefined)} footer={null}><Table size="small" pagination={false} rowKey="version" dataSource={noticeWorkflowHistory ?? []} columns={[{ title: "版本", dataIndex: "version" }, { title: "操作", render: (_: unknown, item: { version: number }) => <Button onClick={() => void restoreNoticeHistory(item.version)}>恢复为新版本</Button> }]} /></Modal></>;
  const resultSummary = page === "history" ? <div className="result-summary"><Card><Typography.Text type="secondary">全部任务</Typography.Text><Typography.Title level={3}>{tasks.length}</Typography.Title></Card><Card><Typography.Text type="secondary">成功成品</Typography.Text><Typography.Title level={3}>{tasks.filter((item) => item.status === "success").length}</Typography.Title></Card><Card><Typography.Text type="secondary">待处理失败</Typography.Text><Typography.Title level={3}>{tasks.filter((item) => item.status === "failed").length}</Typography.Title></Card><Card><Typography.Text type="secondary">生成批次</Typography.Text><Typography.Title level={3}>{batches.length}</Typography.Title></Card></div> : null;
  const auditTimeline = auditPreview ? <Card className="audit-timeline" title={`任务 #${auditPreview.task_id} 审计时间线`}><Space direction="vertical" className="wide">{auditPreview.events.map((event) => <div className="audit-event" key={event.id}><Typography.Text strong>{event.action}</Typography.Text><Typography.Text type="secondary">{event.created_at}</Typography.Text><Typography.Paragraph>{event.detail || "无附加说明"}</Typography.Paragraph></div>)}</Space></Card> : null;
  const loadingPanel = loading ? <Alert className="loading-panel" type="info" message="正在加载工作区数据" showIcon /> : null;
    return <Layout className="shell"><Layout.Content className="shell-top">{loadingPanel}{page === "dashboard" && dashboard}{pathGuide}{modeCenter}{modeSetup}{page === "tasks" && <>{wizardPanel}{workflow?.mode === "template_native" && <NativeWorkflowImprovements configured={Boolean(workflow.notice_config)} version={workflow.notice_config_version} executionMode={workflow.notice_config?.execution_mode} />}{workflowMatchPanel}</>}{assetToolbar}{mappingCenterPanel}{resultSummary}{auditTimeline}{workbookProfilePanel}</Layout.Content>
      <Layout.Sider theme="light"><div className="brand">Excel Flow</div><Menu selectedKeys={[page]} onClick={(event) => setPage(event.key)} items={[{ key: "dashboard", label: "工作台" }, { key: "modes", label: "模式中心" }, { key: "templates", label: "模板中心" }, { key: "mapping-center", label: "工作流配置" }, { key: "tasks", label: "生成向导" }, { key: "history", label: "结果中心" }]} /></Layout.Sider>
      <Layout><Layout.Content className="content"><Typography.Title>Excel 工作流自动生成平台 <Button onClick={() => setNoticeConfigOpen(true)}>通报配置</Button></Typography.Title>{error && <Alert closable message={error} type="error" onClose={() => setError(undefined)} />}<Modal title="通报配置" open={noticeConfigOpen} onCancel={() => setNoticeConfigOpen(false)} onOk={() => setNoticeConfigOpen(false)}><Space direction="vertical" className="wide"><Input value={noticeConfig.title} onChange={(event) => updateNoticeConfig("title", event.target.value)} placeholder="通报标题" /><Input value={noticeConfig.period} onChange={(event) => updateNoticeConfig("period", event.target.value)} placeholder="统计周期" /><Input value={noticeConfig.publisher} onChange={(event) => updateNoticeConfig("publisher", event.target.value)} placeholder="发布单位" /><Input value={noticeConfig.as_of_date} onChange={(event) => updateNoticeConfig("as_of_date", event.target.value)} placeholder="数据截止日期" /><Input value={noticeConfig.signature} onChange={(event) => updateNoticeConfig("signature", event.target.value)} placeholder="落款" /><Input value={noticeConfig.notes} onChange={(event) => updateNoticeConfig("notes", event.target.value)} placeholder="备注" /></Space></Modal><Modal title="任务审计" open={Boolean(auditPreview)} onCancel={() => setAuditPreview(undefined)} footer={null}><Typography.Paragraph>SHA-256：{auditPreview?.output_sha256 || "未生成"}</Typography.Paragraph><Table size="small" pagination={false} rowKey="id" dataSource={auditPreview?.events ?? []} columns={[{ title: "时间", dataIndex: "created_at" }, { title: "操作", dataIndex: "action" }, { title: "详情", dataIndex: "detail" }]} /></Modal><Modal title="映射关系追溯" open={Boolean(mappingTrace)} onCancel={() => setMappingTrace(undefined)} footer={null} width={1100}><Space direction="vertical" className="wide"><Typography.Text>工作流：{mappingTrace?.workflow_name} / 模式：{mappingTrace?.mode}</Typography.Text><Typography.Text>模板版本：{mappingTrace?.template_version} / 规则版本：{mappingTrace?.mapping_rule_version ?? "未保存"} / 快照：{mappingTrace?.mapping_snapshot_id ?? "未绑定"}</Typography.Text><Typography.Text>公式计算顺序：{mappingTrace?.dependency_order.join(" -> ") || "无"}</Typography.Text><Table size="small" pagination={false} rowKey={(item) => `${item.target}-${item.source_kind}`} dataSource={mappingTrace?.rules ?? []} columns={[{ title: "模板输出列", dataIndex: "target" }, { title: "来源类型", dataIndex: "source_kind" }, { title: "基础数据字段", dataIndex: "source_field" }, { title: "公式", dataIndex: "expression" }, { title: "依赖字段", render: (_: unknown, item: MappingTrace["rules"][number]) => item.dependencies?.join(", ") }, { title: "条件", render: (_: unknown, item: MappingTrace["rules"][number]) => item.operator ? `${item.operator}: ${String(item.value ?? "")}` : "" }]} /></Space></Modal>
       {page === "templates" && <Card title="模板管理" extra={<Upload beforeUpload={(file) => uploadTemplate(file)} showUploadList={false}><Button icon={<UploadOutlined />}>上传模板</Button></Upload>}><Table rowKey="id" dataSource={templates} columns={templateColumns} /><Typography.Title level={4}>已保存工作流</Typography.Title><Table rowKey="id" dataSource={workflows} columns={workflowColumns} pagination={false} /><Modal title={tutorial ? `教程：${tutorial.title}` : "教程"} open={Boolean(tutorial)} onCancel={() => setTutorial(undefined)} footer={null} width={1000}><Typography.Text type="secondary">复杂度：{tutorial?.complexity}</Typography.Text><pre className="tutorial-content">{tutorial?.content}</pre></Modal><Modal title="模板预览" open={previewOpen} onCancel={() => setPreviewOpen(false)} footer={null} width={900}><Tabs items={previewTabs} /></Modal><Modal title="模板版本" open={Boolean(templateVersions)} onCancel={() => setTemplateVersions(undefined)} footer={null}><Table rowKey="id" pagination={false} dataSource={templateVersions?.versions ?? []} columns={[{ title: "名称", dataIndex: "name" }, { title: "版本", dataIndex: "version" }, { title: "创建时间", dataIndex: "created_at" }, { title: "公式", render: (_: unknown, item: Template) => item.has_formula ? "含公式" : "无公式" }]} /></Modal><Modal title="公式检查与依赖" open={Boolean(formulaReport)} onCancel={() => { setFormulaReport(undefined); setFormulaDependencies(undefined); }} footer={null} width={1000}><Typography.Paragraph>公式数量：{formulaReport?.formula_count ?? 0}</Typography.Paragraph>{formulaReport?.valid ? <Alert type="success" message="公式引用检查通过" /> : <Alert type="error" message={(formulaReport?.issues ?? []).map((issue) => issue.message).join("；")} />}<Table size="small" pagination={{ pageSize: 10 }} rowKey={(item) => `${item.sheet}!${item.cell}`} dataSource={formulaDependencies?.dependencies ?? []} columns={[{ title: "公式单元格", render: (_: unknown, item: FormulaDependencies["dependencies"][number]) => `${item.sheet}!${item.cell}` }, { title: "公式", dataIndex: "formula" }, { title: "引用单元格", render: (_: unknown, item: FormulaDependencies["dependencies"][number]) => item.references.map((reference) => `${reference.sheet}!${reference.cell}`).join("，") || "无直接引用" }]} /></Modal></Card>}
       {page === "dag" && <Card title="模式 B 流程设计器" extra={<Space><Button onClick={() => setPage("templates")}>返回</Button><Button type="primary" onClick={() => void saveDag()}>保存流程</Button><Button onClick={() => void runTask()}>运行流程</Button></Space>}><Space wrap>{["data_source", "field_mapping", "formula", "condition", "write_template", "output_file"].map((type) => <Button key={type} onClick={() => addDagNode(type)}>添加 {type}</Button>)}</Space><div className="dag-canvas"><ReactFlow nodes={dagNodes.map((node) => ({ ...node, data: { ...node.data, label: node.data.nodeType } }))} edges={dagEdges} onNodesChange={handleDagNodesChange} onEdgesChange={handleDagEdgesChange} onConnect={(connection: Connection) => setDagEdges((current) => addEdge(connection, current))} onNodeClick={(_event, node) => setSelectedDagNodeId(node.id)} fitView><MiniMap /><Controls /><Background /></ReactFlow></div><Card size="small" title={selectedDagNode ? `节点配置：${selectedDagNode.data.nodeType}` : "节点配置"}>{renderDagConfigForm()}</Card></Card>}
       {page === "tasks" && <Card title="任务执行"><Space direction="vertical" size="large" className="wide"><Typography.Text>工作流：{workflow?.name ?? "请先编辑工作流"}</Typography.Text><Upload beforeUpload={(file) => upload("/data-sources/upload", file)} showUploadList={false}><Button icon={<UploadOutlined />}>上传基础数据</Button></Upload><Space><Select value={dataSourceId} onChange={setDataSourceId} placeholder="选择数据源" options={dataSources.map((source) => ({ label: source.name, value: source.id }))} /><Button onClick={() => void showQualityReport()}>数据质量检查</Button></Space><Button type="primary" onClick={() => void runTask()}>生成 Excel</Button><Select mode="multiple" value={batchSourceIds} onChange={setBatchSourceIds} placeholder="选择多个数据源批量生成" options={dataSources.map((source) => ({ label: source.name, value: source.id }))} /><Button onClick={() => void runBatch()}>批量生成</Button>{task && <Card size="small" title={`任务 #${task.id}`}><Tag color={task.status === "success" ? "green" : task.status === "failed" ? "red" : "blue"}>{task.status}</Tag>{task.calculation_engine && <Typography.Text type="secondary">计算引擎：{task.calculation_engine}</Typography.Text>}{task.status === "running" && <Progress percent={50} status="active" />}{task.error_log && <Alert message={task.error_log} type={task.status === "success" ? "info" : "error"} />}{task.status === "success" && <Button type="link" href={`/api/tasks/${task.id}/download`}>下载生成文件</Button>}</Card>}</Space><Modal title="数据质量报告" open={Boolean(qualityReport)} onCancel={() => setQualityReport(undefined)} footer={qualityReport ? <Button href={`/api/data-sources/${dataSourceId}/quality-report/download`}>下载 Excel 报告</Button> : null} width={900}>{qualityReport && <><Space><Typography.Text>数据行数：{qualityReport.row_count}</Typography.Text><Typography.Text>字段数：{qualityReport.field_count}</Typography.Text><Typography.Text>问题数：{qualityReport.issue_count}</Typography.Text></Space>{qualityReport.valid ? <Alert type="success" message="数据质量检查通过" /> : <Alert type="warning" message="发现数据质量问题，请处理后再生成" />}<Table size="small" pagination={{ pageSize: 10 }} rowKey={(item) => `${item.field}-${item.type}`} dataSource={qualityReport.issues} columns={[{ title: "字段", dataIndex: "field" }, { title: "类型", dataIndex: "type" }, { title: "说明", dataIndex: "message" }]} /></>}</Modal></Card>}
         {page === "history" && <Card title="任务历史" extra={batchTaskIds.length > 0 && <Button type="primary" href={`/api/tasks/batch-download?${batchTaskIds.map((id) => `task_ids=${id}`).join("&")}`}>下载本批次 ZIP</Button>}><Card size="small" title="生成批次"><Table size="small" rowKey="batch_id" pagination={false} dataSource={batches} columns={[{ title: "批次", dataIndex: "batch_id" }, { title: "状态", dataIndex: "status", render: (value: string) => <Tag>{value}</Tag> }, { title: "任务数", dataIndex: "task_count" }, { title: "成功", dataIndex: "success_count" }, { title: "失败", dataIndex: "failed_count" }, { title: "质量问题", render: (_: unknown, item: BatchSummary) => item.quality_checked_count ? `${item.quality_issue_count}（${item.quality_invalid_count} 个数据源）` : "未检查" }, { title: "通报标题", render: (_: unknown, item: BatchSummary) => item.notice_config?.title || "默认通报" }, { title: "操作", render: (_: unknown, item: BatchSummary) => <Space><Button type="link" href={`/api/tasks/batch-download?${item.tasks.filter((taskItem) => taskItem.output_path).map((taskItem) => `task_ids=${taskItem.id}`).join("&")}`}>下载成功结果</Button>{item.failed_count > 0 && <Button onClick={() => void retryBatch(item)}>重试失败</Button>}</Space> }]} /></Card><Table rowKey="id" dataSource={tasks} columns={taskColumns} /><Modal title="成品 Excel 预览" open={Boolean(finalPreview)} onCancel={() => setFinalPreview(undefined)} footer={null} width={1100}><Typography.Paragraph>Sheet 数量：{finalPreview?.sheet_count ?? 0}</Typography.Paragraph><Tabs items={(finalPreview?.sheets ?? []).map((sheet) => { const headers = sheet.rows[0] ?? []; const rows = sheet.rows.slice(1).map((row, index) => ({ key: index, values: row })); const columnsForSheet = headers.map((_header, index) => ({ title: String(headers[index] ?? `列 ${index + 1}`), render: (_: unknown, item: { values: unknown[] }) => String(item.values[index] ?? "") })); return { key: sheet.title, label: `${sheet.title} (${sheet.max_row - 1} 行)`, children: <Table size="small" pagination={{ pageSize: 20 }} dataSource={rows} columns={columnsForSheet} /> }; })} /></Modal><Modal title="公式结果预览" open={Boolean(formulaPreview)} onCancel={() => setFormulaPreview(undefined)} footer={null} width={1000}><Typography.Paragraph>公式数量：{formulaPreview?.formula_count ?? 0}</Typography.Paragraph><Tabs items={(formulaPreview?.sheets ?? []).map((sheet) => ({ key: sheet.title, label: `${sheet.title} (${sheet.formula_count})`, children: <Table size="small" pagination={{ pageSize: 20 }} rowKey="cell" dataSource={sheet.results} columns={[{ title: "单元格", dataIndex: "cell" }, { title: "公式", dataIndex: "formula" }, { title: "计算值", dataIndex: "value", render: (value: unknown) => String(value ?? "未缓存") }, { title: "错误", dataIndex: "error", render: (value: string | null) => value ? <Tag color="red">{value}</Tag> : <Tag color="green">正常</Tag> }]} /> }))} /></Modal></Card>}
    </Layout.Content></Layout>
  </Layout>;
}

export { App };
